variables:
# MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"

# define list of files that should be cached
cache:
  key: maven-repository-cache
  paths:
  - /root/.m2
image: maven:3.6-jdk-8-alpine

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: "mvn clean package"

unit-test:
  stage: test
  script: "mvn -U test"
  
deploy:
  stage: deploy
  script:
  - "mvn deploy"
  environment:
    name: oss-sonatype
    url: https://oss.sonatype.org/
  when: manual
