image: maven:3.6-jdk-8-alpine
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: "mvn clean package"

unit-test:
  stage: test
  script: "mvn -U test"
  
deploy:
  stage: deploy
  script:
  - "mvn deploy"
  when: manual
